/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smpro;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;


/**
 *
 * @author 1412625
 * this class is responsible for creation of every message sent
 * the messages generated by this class is of three types
 * Message Type 1 – contains the details of 1 sale E.g apple at 10.0p
 * Message Type 2 – contains the details of a sale and the number of occurrences
 * of  that sale. E.g 20 sales of apples at 10p each.
 * Message Type 3 – contains the details of a sale and an adjustment operation
 * to be applied to all stored sales of this product type. Operations can be
 * add, subtract, or multiply e.g Add 20p apples would instruct your application
 * to add 20p to each sale of apples you have recorded.
 * As it was given in the requirement
 */
public class TransactionMessages {

    private static List<String> produts = new ArrayList<>();
    private static Map<String, Double> spec = new HashMap();
    
    static{
        produts.add("apple");
        produts.add("banana");
        produts.add("mango");
        produts.add("pear");
        produts.add("orange");
        produts.add("berry");
        spec.put("apple", 12.00);
        spec.put("banana", 3.00);
        spec.put("mango", 5.00);
        spec.put("pear", 1.50);
        spec.put("orange", 3.06);
        spec.put("berry", 2.00); 
    }
    
    public static void main(String[] args) {
        
        System.out.println(createTransactionMessage(new Random()));
    }

    public static List<String> getProduts() {
        return produts;
    }

    public static void setProduts(List<String> produts) {
        TransactionMessages.produts = produts;
    }
    public static String createTransactionMessage(Random r) {
        
        String messageType = "";
        Random price = r;
        Random quantity = r;
        Random selector = r;
        Random productIndex = r;
        String product = produts.get(productIndex.nextInt(produts.size()));
        int q = 0;
        int z = 0;
   
        switch(selector.nextInt(3) +1){       
            case 1:
                messageType = product+" at "+spec.get(product)+"p";
                break;
                
            case 2:
                messageType = (quantity.nextInt(20)+1)+" sales of "+product+" at "+spec.get(product)+"p each";
                break;
                
            default:
                Random getOperation = new Random();
                int val = getOperation.nextInt(3) + 1;
        switch (val) {
            case 1:
                messageType = "Add";
                break;
            case 2:
                messageType = "Subtract";
                break;
            default:
                messageType = "Multiply";
                break;
        }
                messageType += " "+(price.nextInt(10) + 1)+".00p "+product;
                break;
        
        }
        return  messageType;
        
    }
           
}
